services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_DB: FakeData
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: postgres
    volumes:
      - .:/bitnami/postgresql
    ports:
      - '5432:5432'

volumes:
  data:
    driver: local